[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  APP_URL = "localhost:3000"
  GITHUB_SECRET="your-github-client-secret"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="121212323"
  GOOGLE_SITE_VERIFICATION_ID="123123"