[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  # Skip env validation during build
  CI = "true"
  # Provide fallback values for build
  DATABASE_URL = "postgresql://postgres.xcmbintaeueklcrvbfez:Test@123@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"
  APP_URL = "https://conf-quest.netlify.app"

[context.production.environment]
  # Update these in your Netlify dashboard
  DATABASE_URL = "$DATABASE_URL"
  APP_URL = "$DEPLOY_URL"
  NEXTAUTH_URL = "$DEPLOY_URL"
  NEXTAUTH_SECRET = "$NEXTAUTH_SECRET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200